method: random
metric:
  name: loss
  goal: minimize
parameters:
  learning_rate: [1e-2, 1e-3, 1e-4, 3e-4, 3e-5, 1e-5]
  batch_size: [32, 64, 96, 128]
  image_resolution: [224, 256, 299]
  MNIST: False
  n_classes: 10
  optimizer: [adam, sgd]
  num_epochs: [2, 5, 10]